'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Gang
    Public Property Id As Integer
    Public Property Number As Integer
    Public Property StartTime As System.TimeSpan
    Public Property EndTime As System.TimeSpan
    Public Property PreviousDay As Boolean

End Class
