'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaskData
    Public Property Id As Integer
    Public Property SystemTaskType_id As Integer
    Public Property ZoneShipper As Nullable(Of Integer)
    Public Property ZoneConsignee As Integer
    Public Property UserTaskType As String
    Public Property Norm As Double
    Public Property Employee_id As Integer
    Public Property TaskDate As Date
    Public Property YearNum As Integer
    Public Property MonthNum As Integer
    Public Property WeekNum As Integer
    Public Property DayNum As Integer
    Public Property WeekdayNum As Integer
    Public Property HourNum As Integer
    Public Property TaskPreviousDate As Date
    Public Property PreviousYearNum As Integer
    Public Property PreviousMonthNum As Integer
    Public Property PreviousWeekNum As Integer
    Public Property PreviousDayNum As Integer
    Public Property PreviousWeekdayNum As Integer
    Public Property GangNum As Integer

End Class
