'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ExtraData
    Public Property Id As Integer
    Public Property xDate As Date
    Public Property ZoneShipper As Nullable(Of Integer)
    Public Property QtyUnloadedLPN As Integer
    Public Property QtyOrders As Integer
    Public Property AvgQtyPcs As Integer

End Class
