'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class PipelineData
    Public Property Id As Integer
    Public Property XDate As Date
    Public Property VolumeCargo As Double
    Public Property VolumeBox As Double
    Public Property QtyBoxesNotPassedWeightControl As Integer
    Public Property QtyBoxesPassedWeightControl As Integer

End Class
