'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class TaskData
    Public Property Id As Integer
    Public Property SystemTaskType_id As Integer
    Public Property ZoneShipper As Nullable(Of Integer)
    Public Property RowShipper As String
    Public Property ZoneConsignee As Nullable(Of Integer)
    Public Property UserTaskType As String
    Public Property Norm As Double
    Public Property Employee_id As Integer
    Public Property TaskDate As Date
    Public Property YearNum As Integer
    Public Property MonthNum As Integer
    Public Property WeekNum As Integer
    Public Property DayNum As Integer
    Public Property WeekdayNum As Integer
    Public Property HourNum As Integer
    Public Property TaskDateOnShifts As Date
    Public Property YearNumOnShifts As Integer
    Public Property MonthNumOnShifts As Integer
    Public Property WeekNumOnShifts As Integer
    Public Property DayNumOnShifts As Integer
    Public Property WeekdayNumOnShifts As Integer
    Public Property GangNum As Integer
    Public Property QtyTasks As Integer

End Class
