'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class ZoneGroup
    Public Property Id As Integer
    Public Property Zone As Integer
    Public Property GroupA As Integer
    Public Property GroupB As Integer
    Public Property UpDown As Boolean
    Public Property PickingNorm As Nullable(Of Double)

End Class
