'------------------------------------------------------------------------------
' <auto-generated>
'     Этот код создан по шаблону.
'
'     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
'     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Zone
    Public Property Id As Integer
    Public Property ZoneNum As Integer
    Public Property MainGroup As Integer
    Public Property CustomGroup As Integer
    Public Property UpDown As Boolean
    Public Property PickingNorm As Double

End Class
